### PR TITLE
Add build status api support

### PR DESCRIPTION
**Pull request by ynojima**
BitBucket Server provides build status API.
API doc: https://developer.atlassian.com/static/rest/bitbucket-server/4.5.1/bitbucket-build-rest.html

By using this API, pullrequest builder can tell BitBucket Server whether the pullrequest pass CI test or not, and BitBucket Server utilize build status to determine to block merge.

\* This PR is same as https://github.com/jenkinsci/stash-pullrequest-builder-plugin/pull/14.

### CODE REVIEW

**Comment by nemccarthy** [comment]
Why would we do this as opposed to using the stash notifier plugin?

**Comment by mandrizzle** [comment]
That plugin requires a bunch of dependencies to install to literally make a single post request. We might also be able to get rid of the comments this plugin leaves behind if we check the build status via the build status api

**Comment by thomaseizinger** [comment]
@nemccarthy The stash build-status API is relatively new. Their blog-post explaining the new features is from December '15. (https://developer.atlassian.com/stash/docs/latest/how-tos/updating-build-status-for-commits.html)
I think that utilizing this API would be the way to go as stash can actually pickup this information and prevent merging the PR if the builds fails and stuff like that.
I am very interested in having this feature, so I would happily volunteer to pick up work on this pull-request if there is still anything left to do.

**Comment by thomaseizinger** [comment]
I just noticed the "stash notifier" plugin in the plugin repository of jenkins. So I guess this PR is kinda obsolete.

**Comment by nemccarthy** [comment]
This to me seems to be supported by the stash notifier plugin, and this plugin works with it. Closing for now.

**Pull request closed without merging**
