### PR TITLE
Use Credentials to store Stash login username and password

### PR DESCRIPTION
**Pull request by nickbroon**
Just as the title says :-)
StashBuildTrigger class now keeps a Jenkins Credentials Object instead of Username and Password, with this exposed in the config.jelly GUI using the appropriate Jelly expected Getters and doFillCredentialsIdItems methods.
Tested, and works fine in my setup, with credentials listed, and the configured one remembered.

### CODE REVIEW

**Comment by nickbroon** [comment]
@nemccarthy should I submit this PR against https://github.com/jenkinsci/stash-pullrequest-builder-plugin?

**Comment by nemccarthy** [comment]
Awesome! Thanks for this @nickbroon

**Comment by byF** [comment]
Is this planned for 1.4.3?

**Comment by nickbroon** [comment]
As it's not backwards compatible it will have to be at least a 1.5 release.
(It ignores/removes the previous username/password stored directly in the plugin config. The user needs to create a new entry in the credentials store)

**Comment by benheymink** [comment]
Any update on the merge @nemccarthy? Been watching this one :)

**Pull request merged**
