### PR TITLE
Feature/use git scm as provider

### PR DESCRIPTION
**Pull request by laurentverbruggen**
Use Git SCM as provider for hostname and credentials needed for the pull request builder.

Now it is also possible to verify pull requests from another fork (while previously it would only work in the same repository, or at least with the merge before build feature). Prerequisite is that you add +refs/pull-requests/:refs/remotes/origin/pr/ as refspec.

Additionally you can filter on the target branch which makes you able to restrict checking pull requests on a specific (release) branch.

And last but not least, support for global environment variables has been added.

Note: I think fixed the issue with SSH, but please test it because it is hard for me to test this functionality

### CODE REVIEW

**Comment by martinda** [comment]
This PR looks like it bring a set of immensely useful features. Shouldn't be split into multiple PRs? I am trying v1.3.1 of the plugin. What Stash REST API features are you using, and can it be made optional, in other words, if I cannot put the credentials in Jenkins, what will I be missing?

**Comment by nemccarthy** [comment]
@martinda This plugin needs to be able to auth with stash and post comments otherwise it won't work.

**Comment by nickbroon** [comment]
:+1:

**Comment by nickbroon** [comment]
I rebased this code and it can be found at #58, so perhaps this PR can be closed.

**Pull request closed without merging**
