### PR TITLE
Customize CI Build Phrases

### PR DESCRIPTION
**Pull request by soasme**
I think `test this please` is too verbose to type (and is easy to make typo).
Allowing customize `ciBuildPhrases` is much more flexible, just like `ciSkipPhrases`.

~~PS. I have no idea how to test jenkins plugin, so this pr is still not tested :(~~

### CODE REVIEW

**Comment by soasme** [comment]
@nemccarthy code review please

**Comment by soasme** [comment]
It's being tested and just work :)

configure

screenshot

**Comment by nightwolfzor** [comment]
This is a good change but would it make more sense as a global config setting?

**Comment by nemccarthy** [comment]
+1 for some global config but there also seems a need for this to be configured per project. Thanks for the PR!

**Pull request merged**
