### PR TITLE
Use git scm as provider

### PR DESCRIPTION
**Pull request by nickbroon**
I rebased/squashed, laurentverbruggen:feature/use-git-scm-as-provider as originally submitted in #26

### CODE REVIEW

**Comment by nickbroon** [comment]
Ignore!
Still suffers from a problem with invalid URI.
```
WARNING: stashpullrequestbuilder.stashpullrequestbuilder.StashBuildTrigger.run() failed for hudson.model.FreeStyleProject@18266395[code_pullrequest_checker]
java.lang.IllegalArgumentException: Invalid stash URI git@example.com/~user/code.git
at stashpullrequestbuilder.stashpullrequestbuilder.stash.StashApiClient.<init>(StashApiClient.java:62)
        at stashpullrequestbuilder.stashpullrequestbuilder.StashRepository.init(StashRepository.java:142)
        at stashpullrequestbuilder.stashpullrequestbuilder.StashPullRequestsBuilder.run(StashPullRequestsBuilder.java:29)
        at stashpullrequestbuilder.stashpullrequestbuilder.StashBuildTrigger.run(StashBuildTrigger.java:182)
```

**Comment by nemccarthy** [comment]
Thanks @nickbroon does this work with different URIs? Could we just add credentials support instead of trying to get them from the git plugin

**Comment by nickbroon** [comment]
Actually, now that I think about it, I think your right, just adding credential support to the plugin keeps it simple. The URI for the stash instance used for the PR trigger is distinct from the URI used for the Git repository, so trying to combine the handling is over kill.

**Comment by nemccarthy** [comment]
Would you have time to work on this? Would be a killer feature. Make a great release for 1.5 which should also have the ability to avoid posting messages to Stash when build starts

**Comment by nickbroon** [comment]
I'll start having a look into this. Don't know much about Jenkins in general and the credentials in particular, but I'm sure other plugins to look at, and conceptually its seem straightforward to replace the user/password fields with credentials selection box.
Are you working on the serialise support for local storage to allow better PR comment control? :-)

**Comment by nickbroon** [comment]
I'm making slow but steady progress:
https://github.com/nickbroon/stash-pullrequest-builder-plugin/commit/adce271a26645b8b7bb1784f1e15ec44e8e146a2

I've just got to pass the credential down to the StashApiClient class, and then do some testing.

Though I've just spotted you've got a similar branch:
https://github.com/nickbroon/stash-pullrequest-builder-plugin/commit/654443365b9068a0f10b6b61508f1377f93af163

I'll complete the work I've begun, and submit a PR for your consideration.

**Comment by nemccarthy** [comment]
Awesome, thanks @nickbroon

**Comment by nickbroon** [comment]
I completed what I thought was all the coding but hitting a crash at moment.
Code and backtrace at: 
https://github.com/nemccarthy/stash-pullrequest-builder-plugin/commit/877340538d532d3e4e20851260b48c6fa5bf91d8?_pjax=%23js-repo-pjax-container#commitcomment-14529030

**Comment by nickbroon** [comment]
https://github.com/nickbroon/stash-pullrequest-builder-plugin/commits/stash_credentials
This one work. Minor issue of it not showing the selected Credential in the drop down box after saving/reloading the config page, which I'm looking into, but it does work.

**Comment by nickbroon** [comment]
Closing in favour of #61

**Pull request closed without merging**
