### PR TITLE
SocketTimeout causes rebuilding a PR multiple times

### PR DESCRIPTION
**Pull request by MartinMReed**
Issue #101: SocketTimeout causes rebuilding a PR multiple times.
If a SocketTimeoutException is thrown while reading any of the comment responses, it will be consumed and an empty list will be returned for the comments. The empty list then triggers the build to run again because the plugin thinks no previous attempts were made.

### CODE REVIEW

**Comment by nickbroon** [comment]
:+1:

**Comment by nemccarthy** [comment]
Could we fix conflicts and ill merge this in thanks

**Comment by MartinMReed** [comment]
@nemccarthy Done.

**Comment by Macarse** [comment]
@nemccarthy can you push an update with this?

**Comment by MartinMReed** [comment]
@nemccarthy please merge.

**Comment by batmat** [comment]
Unmaintained repo, unrelated to the Jenkins Project FYI.
See https://github.com/nemccarthy/stash-pullrequest-builder-plugin/issues/158

**Pull request closed without merging**
