### PR TITLE
Changes to how variables are added to the build

### LINKED ISSUE #84: Missing variables
Jenkins version: 2.3

It seems that variables aren't being made available to Jenkins anymore resulting in the following:

> git -c core.askpass=true fetch --tags --progress git@git.xxx.io:xxx/xxx.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/${sourceBranch}^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/${sourceBranch}^{commit} # timeout=10
 > git rev-parse origin/${sourceBranch}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Unable to expand commit SHA value
org.jenkinsci.plugins.tokenmacro.MacroEvaluationException: Unrecognized macro 'sourceCommitHash' in '${sourceCommitHash}'
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expand(TokenMacro.java:207)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:246)
	at org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:232)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.lookupCommitSha1s(StashNotifier.java:287)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:247)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:205)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
found no commit info
Finished: FAILURE

Has anyone else been receiving these issues since upgrading Jenkins?

### PR DESCRIPTION
**Pull request by eirikwang**
Jenkins issue SECURITY-180 added a new security feature that only lets declared variables into the build. This fix rewrites the plugin to use environment contributor which is the proper way to give properties to a build. 

This closes #84

### CODE REVIEW

**Comment by nickbroon** [comment]
:+1:

**Comment by nickbroon** [comment]
@nemccarthy, can this be merged?
As mentioned in #84 this is critical fix to be able to update Jenkins past 2.2

**Comment by Macarse** [comment]
what's blocking this PR?

**Comment by dreis2211** [comment]
+1

**Comment by tiberiuzuld** [comment]
+1

**Comment by PixnBits** [comment]
Having access to ${pullRequestCommit} is the last step for PR notifications for my team, project member reviews of this PR are very appreciated by us (and particularly me, as I'm the reporting robot for now :P)

**Comment by PixnBits** [comment]
(belated) thanks, @nemccarthy :)

**Pull request merged**
